### ISSUE TITLE
Option to specify binners to use/skip

### ISSUE THREAD

**Issue by Kirk3gaard** [Serka-M/mmlong2#2]
Hi

I think it would be great to have an option to use/skip a specified list of binning tools.
e.g. 
--use_binners "graphmb,semibin"
--skip_binners "graphmb,semibin"

Best regards
Rasmus

**Comment by StevenJRobbins** [comment]
This would be very useful ;-). Also to pass additional arguments to the binners if you want to tweak them. E.g. to set the read-type to short or long depending on your usage for SemiBin2.
