### ISSUE TITLE
Would it be possible to provide bins and start from the middle of mmlong2 pipeline?

### ISSUE THREAD

**Issue by MingHHaii** [Serka-M/mmlong2#5]
Hello Serka-M, I currently have some bins generated through other methods, but I would like to proceed with the latter part of mmlong2 to evaluate these bins, like to summarize the number of rRNAs and tRNAs. Could you please kindly guide me on how to proceed with this?

**Comment by Serka-M** [comment]
Hello, this is possible by creating some mock files and then touching them with Snakemake, although it would require some more advanced Snakemake usage.

An upcoming updated version of the pipeline will make this way easier.

**Comment by MingHHaii** [comment]
> Hello, this is possible by creating some mock files and then touching them with Snakemake, although it would require some more advanced Snakemake usage.
> 
> An upcoming updated version of the pipeline will make this way easier.

Thanks a lot for your kind reply. Would it be possible to use these mock files in advance, as we are waiting for such analysis ? And when the updated version of mmlong2 will be released?

**Comment by Serka-M** [comment]
Hello again, the new version is in active development right now and so it is difficult to provide and ETA at the moment.

For analyzing MAGs obtained from different tools, it might make more sense to use other, more established workflows.
